name: Module Test Workflow

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Package
      run: |
        mkdir release
        cp LICENSE README.MD src/Cfg_Docker/dockerfile src/scr_paperPassBox/boxInitialize.sh release/
        zip -r release.zip release/

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release.zip

    - name: Deploy
      run: |
        cp -R release deployment
        cd deployment
        docker build -t module-container -f src/Cfg_Docker/dockerfile .
        docker run -d --name module-test-container -p 2222:22 module-container

    - name: Test
      run: |
        cp -R scr_paperPassBox_test test
        cd test
        pipenv install
        pipenv run pytest

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: test/*.xml
