name: moduleTest

on: [push]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up variables
        run: echo "RELEASE_VERSION=v$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Prepare Files
        run: |
          mkdir release
          cp LICENSE release/
          cp README.md release/
          cp docker/dockerfile release/
          cp src/setup.sh release/
          zip -r release.zip release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip

      - name: Build and Run Docker Container
        run: |
          mkdir deployment
          cp -r release/* deployment/
          cd deployment
          docker build -t myapp:latest -f dockerfile .
          docker run -d -p 2222:22 --name myapp_container myapp:latest

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if asset already uploaded
        id: check_asset
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/:owner/:repo/releases/tags/:tag
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          tag: ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

